# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run detekt
      uses: gradle/gradle-build-action@v2
      with:
        arguments: detekt
    - name: Run unit tests
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test

  build:

    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: buildFatJar
    - name: Upload JAR
      uses: actions/upload-artifact@v3
      with:
        name: pelata-jar
        path: build/libs/net.pelata.pace-all.jar
  
  deploy:

    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'

    steps:
    - name: Download JAR
      uses: actions/download-artifact@v3
      with:
        name: pelata-jar
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: ${{ secrets.AWS_APPLICATION_NAME }}
        environment_name: ${{ secrets.AWS_ENV_NAME }}
        version_label: ${{github.SHA}}
        region: eu-west-2
        deployment_package: net.pelata.pace-all.jar
      
